### ISSUE TITLE
Audio Stream Switch not working

### ISSUE THREAD

**Issue by b0ogdan** [sudormroot/TheNewPlayer_builds#1]
Hi..Just found your app. Thank you for making it.
I like that is nice and simple but i have a small issue with it..I Have many channels where i need to change the audio stream to the secondary audio stream in english...and the i cannot..i tried the shortcut key "A" but nothing happen...just shows in the top left corner Chapter Change -1->-1. Same with the subtitles..I check the same channel in a different app and it`s working..i can switch the audio and turn on subtitles..does the app have some issue or it`s connected with the codecs that that you app is using?

**Comment by sudormroot** [comment]
Thanks for using my app, b0ogdan, I'm busy recently for catching up a deadline. Basically, current app is a prototype and in developing. In some cases (for specific media files), my app might not correctly switch chapters or channels. Perhaps I'll fix this problem in next version or I can just release my source code in future.

Perhaps you are right, in some cases, for some files, it's associated with codec(s) the app is using.

**Comment by sudormroot** [comment]
Basically, the motivation of this app is designed to watch IPTV streamings, and I want to decode the signals from SDR hardware by receiving analog TV signals (not done yet).

But I also optimized this app a lot for decoding local videos with various formats, especially, the app can harness hardware decoder to decode those videos.
