### ISSUE TITLE
install from brew cask does not work

### ISSUE THREAD

**Issue by b0ogdan** [sudormroot/TheNewPlayer_builds#3]
brew cask install thenewplayerfree does not work... i get this back Error: Cask 'thenewplayerfree' is unavailable: No Cask with this name exists.

thanks

**Comment by sudormroot** [comment]
Yes, the project 'thenewplayerfree' isn't available on brew cask because their policies need my project having at least 50 stars. However, I only have 35 star so far.
Alternatively, I can put the app on AppStore at some point or later we can add this project to brew cask if stars are 50.
