### ISSUE TITLE
Request to realeased a REALEASE

### ISSUE THREAD

**Issue by skykeyjoker** [sudormroot/TheNewPlayer_builds#6]
I'm an archlinux user.
Your app is very useful for me, thank you! And it's more generous for you if you peimit us archlinux users to build a PKGBUILD of your app and upload it to our user repository. To do it, we hope you can realeased a REALEASE to make us convenient to download your app(Some coutries cann't download github files by raw).
Thank you!

**Comment by sudormroot** [comment]
I added a MIT-like license, for your case or legal purpose, you can copy, modify and redistribute my app without any limitation. In your case, you can repack and upload to where you hope. Thanks for using my app.
