### ISSUE TITLE
NextPlayer AppImage fails to run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [sudormroot/TheNewPlayer_builds#7]
NextPlayer AppImage fails to run on Ubuntu xenial:

```
/run/firejail/appimage/.appimage-9155/opt/nextplayer/bin/nextplayer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9155/opt/nextplayer/lib/libavfilter.so.7)

/run/firejail/appimage/.appimage-9155/opt/nextplayer/bin/nextplayer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /run/firejail/appimage/.appimage-9155/opt/nextplayer/lib/libavformat.so.58)
```

To increase compatibility, please build on a system no newer than the oldest still-supported distribution version, which in the case of Ubuntu currently is xenial.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2202

**Comment by sudormroot** [comment]
Thanks for using my app.

Please try https://github.com/sudormroot/nextplayer-project/releases/tag/nextplayer-bin.deepinv15.1.7.5-1.amd64.

This one is built on a variant of old Debian, but should work on old ubuntu. If not, please let me know, I'll build one for old ubuntu.

**Comment by sudormroot** [comment]
I will build on Ubuntu xenial.

**Comment by sudormroot** [comment]
https://github.com/sudormroot/nextplayer-project/releases/tag/nextplayer-bin.linux.1.7.6-1.amd64

Should work on ubuntu xenial.
