### ISSUE TITLE
NextPlayer v1.7.5 crashes on loading any m3u file

### ISSUE THREAD

**Issue by elias137** [sudormroot/TheNewPlayer_builds#8]
NextPlayer v1.7.5 crashes on loading any m3u file. No specific errors in console though (screen attached). Mac OS High Sierra 10.13.6. Any help would be much appreciated!

![Screen Shot 2020-09-03 at 16 25 48](https://user-images.githubusercontent.com/5212070/92121011-72b48580-ee02-11ea-8d0a-21182c27dfb2.png)

**Comment by sudormroot** [comment]
Thank you for the report, I will confirm.

**Comment by sudormroot** [comment]
Hi, the problem is because your macOS is too old that some APIs might have problems running with it.
