### ISSUE TITLE
Browsing between streams restores volume to 100% each time

### ISSUE THREAD

**Issue by liv3010m** [sudormroot/TheNewPlayer_builds#9]
On macOS with nextplayer.app.macos.1.7.5.amd64 build, when changing streams the volume gets restored to 100% and doesn't stay where it was set. Also the volume can't be ajusted till the stream has been completely loaded.

**Comment by sudormroot** [comment]
Please go to the references->setup to set the initial volume. And update to newest version if applicable.

**Comment by liv3010m** [comment]
Thanks!, but I was expecting something to let it stay the same level as the actual playing volume. Can we request this feature?
Mmm 1.7.5 is actually the latest version for macOS.
